# Generated by Django 3.2.16 on 2024-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunkform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
            ],
        ),
    ]
